# Generated manually to keep the project runnable without prebuilt local dependencies.
import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='Category', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=100,verbose_name='аталышы')),('description',models.TextField(verbose_name='түшүндүрмө')),('icon',models.CharField(default='book-open',max_length=40,verbose_name='иконка')),('slug',models.SlugField(allow_unicode=True,blank=True,unique=True))]),
        migrations.CreateModel(name='ContactMessage',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=120)),('email',models.EmailField(max_length=254)),('message',models.TextField()),('is_read',models.BooleanField(default=False)),('phone',models.CharField(blank=True,max_length=32,verbose_name='телефон'))]),
        migrations.CreateModel(name='Course',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('title',models.CharField(default='Аруу жүрөк',max_length=160)),('description',models.TextField()),('is_active',models.BooleanField(default=True))]),
        migrations.CreateModel(name='FAQ',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('question',models.CharField(max_length=240)),('answer',models.TextField()),('category',models.CharField(blank=True,max_length=100)),('order',models.PositiveIntegerField(default=0))],options={'ordering':['order']}),
        migrations.CreateModel(name='NewsCategory',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=100)),('slug',models.SlugField(allow_unicode=True,blank=True,unique=True))]),
        migrations.CreateModel(name='Registration',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('full_name',models.CharField(max_length=160,verbose_name='аты-жөнү')),('phone',models.CharField(max_length=32,verbose_name='телефон')),('email',models.EmailField(blank=True,max_length=254)),('age',models.PositiveSmallIntegerField(verbose_name='жашы')),('city',models.CharField(max_length=100,verbose_name='шаары')),('education_level',models.CharField(choices=[('beginner','Башталгыч'),('intermediate','Орто'),('advanced','Жогорку')],max_length=20,verbose_name='билим деңгээли')),('learning_format',models.CharField(choices=[('offline','Офлайн'),('online','Онлайн'),('either','Экөө тең ылайыктуу')],max_length=20,verbose_name='окуу форматы')),('notes',models.TextField(blank=True,verbose_name='кошумча маалымат')),('status',models.CharField(choices=[('new','Жаңы'),('contacted','Байланышылды'),('accepted','Кабыл алынды'),('declined','Баш тартты')],default='new',max_length=20)),('consent',models.BooleanField(verbose_name='маалыматтарды иштетүүгө макулдук'))]),
        migrations.CreateModel(name='Teacher',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=160,verbose_name='аты-жөнү')),('title',models.CharField(max_length=180,verbose_name='кызматы / адистиги')),('biography',models.TextField(verbose_name='кыскача өмүр баяны')),('experience',models.CharField(blank=True,max_length=150,verbose_name='тажрыйбасы')),('photo',models.ImageField(blank=True,upload_to='teachers/',verbose_name='сүрөт')),('slug',models.SlugField(allow_unicode=True,blank=True,unique=True))]),
        migrations.CreateModel(name='Testimonial',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=120)),('city',models.CharField(max_length=100)),('text',models.TextField()),('photo',models.ImageField(blank=True,upload_to='testimonials/')),('active',models.BooleanField(default=True))]),
        migrations.CreateModel(name='News',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('title',models.CharField(max_length=200)),('excerpt',models.TextField()),('content',models.TextField()),('image',models.ImageField(blank=True,upload_to='news/')),('author',models.CharField(blank=True,max_length=120)),('slug',models.SlugField(allow_unicode=True,blank=True,unique=True)),('published_at',models.DateField(auto_now_add=True,verbose_name='жарыяланган күнү')),('category',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='core.newscategory'))],options={'ordering':['-published_at']}),
        migrations.CreateModel(name='Lesson',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('title',models.CharField(max_length=180,verbose_name='сабактын аталышы')),('description',models.TextField(verbose_name='кыскача түшүндүрмө')),('duration',models.CharField(blank=True,max_length=60,verbose_name='узактыгы')),('materials',models.CharField(blank=True,max_length=180,verbose_name='материалдар')),('status',models.CharField(default='Маалымат жакында жарыяланат',max_length=80,verbose_name='статусу')),('order',models.PositiveIntegerField(default=0)),('category',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='core.category',verbose_name='категория')),('teacher',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='core.teacher',verbose_name='мугалим'))],options={'ordering':['order','title']}),
    ]
